sudo: required
services:
 - docker

before_install:
 - docker build -t zicbrain/docker-react Dockerfile.dev .

script:
 - docker run zicbrain/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "ap-northeast-2"
 app: "docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-ap-northeast-2-014861376267"
 bucket_path: "docker"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"
